### PR TITLE
Updates and fixes for Azure FIles details gathering

### PR DESCRIPTION
**Pull request by joeharlan**
The changes made here solve for the access errors commonly encountered when running the sizing script without the -SkipAzureFiles option.  The change moves to a different AzureRM control plane based approach for gathering the same details and avoids data plane access control limitations.

### CODE REVIEW

**Comment by DamaniN** [comment]
@joeharlan, I'm seeing this error while testing:

```
Finding all subscription(s)...
Getting label information from 12 subscription(s)...
Processing 12 subscription(s)...                                                                                       
Get-AzRmStorageShare: /home/damani/Get-AzureVMSQLInfo.ps1:758                                                          
Line |                                                                                                                 
 758 |            $azFSs = Get-AzRmStorageShare -StorageAccount $azSAPSObject                                          
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                          
     | File is not supported for the account.      
```

As we discussed, this only happens when the account type is Block or Page Blob Premium, which do not support Azure Files. Please add a check for this to remove the error when the account type is Block or Page Blob Premium.

**Comment by DamaniN** [comment]
@joeharlan, please update the documentation with the additional modules that are required. This includes the installation instructions for the PowerShell Modules.

**Comment by DamaniN** [comment]
@joeharlan please review the outputs that I sent and verify that they are consistent between `Get-AzStorageAccount` and `Get-AzRMStorageShare`.

**Comment by joeharlan** [comment]
All matters previously mentioned have been resolved.

**Review by DamaniN — APPROVED** [review]
LGTM

**Pull request merged**
